from django.urls import path
from . import views

urlpatterns = [
    path("", views.project_list, name="project-list"),
    path("ground-truth/", views.ground_truth_list, name="ground-truth-list"),
    path("annotation/tasks/", views.annotation_task_list, name="annotation-task-list"),
    path("clients/<int:pk>/annotation-tasks/new/", views.annotation_task_create, name="annotation-task-create"),
    path("annotation/tasks/<int:pk>/", views.annotation_task_detail, name="annotation-task-detail"),
    path("annotation/tasks/<int:pk>/edit/", views.annotation_task_edit, name="annotation-task-edit"),
    path("annotation/tasks/<int:pk>/delete/", views.annotation_task_delete, name="annotation-task-delete"),
    path("annotation/tasks/<int:pk>/auto-annotation/", views.start_auto_annotation, name="start-auto-annotation"),
    path("annotation/tasks/<int:pk>/auto-annotation/<int:run_pk>/", views.auto_annotation_status, name="auto-annotation-status"),
    path("annotation/tasks/<int:pk>/auto-annotation/<int:run_pk>/cancel/", views.cancel_auto_annotation, name="cancel-auto-annotation"),
    path("system/auto-annotation/", views.auto_annotation_functions, name="auto-annotation-functions"),
    path("annotation/jobs/<int:pk>/", views.annotation_job, name="annotation-job"),
    path("api/annotation/shortcuts/", views.save_annotation_shortcuts, name="save-annotation-shortcuts"),
    path("api/annotation/jobs/<int:pk>/frames/<int:frame_index>/", views.job_frame_data, name="job-frame-data"),
    path("api/annotation/jobs/<int:pk>/frames/<int:frame_index>/save/", views.save_job_frame, name="save-job-frame"),
    path("clients/new/", views.client_project_create, name="client-project-create"),
    path("clients/<int:pk>/edit/", views.client_project_edit, name="client-project-edit"),
    path("clients/<int:pk>/", views.client_project_detail, name="client-project-detail"),
    path("clients/<int:pk>/delete/", views.client_project_delete, name="client-project-delete"),
    path("clients/<int:pk>/labels/<int:label_pk>/edit/", views.project_label_edit, name="project-label-edit"),
    path("clients/<int:pk>/labels/<int:label_pk>/delete/", views.project_label_delete, name="project-label-delete"),
    path("clients/<int:pk>/rules/<int:rule_pk>/delete/", views.rule_delete, name="rule-delete"),
    path("annotation/tasks/<int:pk>/videos/<int:video_pk>/delete/", views.video_delete, name="video-delete"),
    path("projects/new/", views.project_create, name="project-create"),
    path("projects/<int:pk>/annotate/", views.annotate, name="annotate"),
    path("projects/<int:pk>/frames/<int:frame_index>.jpg", views.frame_image, name="frame-image"),
    path("api/projects/<int:pk>/frames/<int:frame_index>/", views.frame_data, name="frame-data"),
    path("api/projects/<int:pk>/frames/<int:frame_index>/save/", views.save_frame, name="save-frame"),
    path("projects/<int:pk>/export/jsonl/", views.export_jsonl, name="export-jsonl"),
]
