# Generated by Django 5.2.14 on 2026-08-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0002_labelclass_confidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruthRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=16)),
                ('coverage', models.CharField(choices=[('partial', 'Partial'), ('exhaustive', 'Exhaustive')], max_length=16)),
                ('video_sha256', models.CharField(max_length=64)),
                ('annotation_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_releases', to='annotations.project')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GroundTruthItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(default='bounding_box', max_length=32)),
                ('frame_index', models.PositiveIntegerField(db_index=True)),
                ('timestamp_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('label', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('source_annotation_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.groundtruthrelease')),
            ],
            options={
                'ordering': ['frame_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('TRITON', 'Triton'), ('KAFKA', 'Kafka'), ('OFFLINE', 'Offline')], max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_targets', to='annotations.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('GT_VALIDATION', 'GT validation'), ('DETECTION', 'Detection model'), ('CLASSIFICATION', 'Classification model'), ('POSE', 'Pose model'), ('RULE', 'Logic rule')], default='GT_VALIDATION', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ground_truth_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='quality.groundtruthrelease')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='annotations.project')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='quality.target')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled'), ('INCONCLUSIVE', 'Inconclusive')], db_index=True, default='QUEUED', max_length=16)),
                ('correlation_id', models.UUIDField(editable=False, unique=True)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('assertion_results', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='quality.testcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='groundtruthrelease',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_gt_release_version'),
        ),
        migrations.AddIndex(
            model_name='groundtruthitem',
            index=models.Index(fields=['release', 'frame_index'], name='quality_gro_release_62c7df_idx'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_target_name'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'version'), name='unique_test_case_version'),
        ),
    ]
