# Generated by Django 5.2.14 on 2026-08-13 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_alter_testrun_correlation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('task', models.CharField(choices=[('OPEN_VOCAB_DETECTION', 'Open-vocabulary detection'), ('VISUAL_GROUNDING', 'Visual grounding'), ('SEGMENTATION', 'Segmentation'), ('VIDEO_REASONING', 'Video reasoning')], max_length=32)),
                ('runtime', models.CharField(choices=[('LOCAL_PYTHON', 'Local Python'), ('TRITON', 'Triton'), ('HTTP', 'HTTP API'), ('GRPC', 'gRPC API')], default='LOCAL_PYTHON', max_length=20)),
                ('model_id', models.CharField(blank=True, help_text='Checkpoint, Hugging Face ID hoặc Triton model name', max_length=240)),
                ('adapter', models.CharField(help_text='Tên adapter trong execution plane', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('license_name', models.CharField(blank=True, max_length=120)),
                ('commercial_use', models.BooleanField(default=False)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
