# Generated by Django 5.2.14 on 2026-08-13 07:21

import django.db.models.deletion
import quality.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_inferencemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencemodel',
            name='model_file',
            field=models.FileField(blank=True, storage=quality.models.ModelStorage(), upload_to='registry/', validators=[quality.models.validate_model_file]),
        ),
        migrations.CreateModel(
            name='UserInferencePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='quality.inferencemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inference_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
