# Generated by Django 5.2.14 on 2026-08-13 07:23

import quality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_remove_sample_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencemodel',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='inferencemodel',
            name='runtime',
        ),
        migrations.AlterField(
            model_name='inferencemodel',
            name='model_file',
            field=models.FileField(storage=quality.models.ModelStorage(), upload_to='registry/', validators=[quality.models.validate_model_file]),
        ),
    ]
