# Generated by Django 5.2.14 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_remove_inferencemodel_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencemodel',
            name='artifact_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inferencemodel',
            name='artifact_type',
            field=models.CharField(choices=[('SINGLE_FILE', 'Single weight file'), ('MODEL_BUNDLE', 'Model bundle')], default='SINGLE_FILE', max_length=20),
        ),
        migrations.AddField(
            model_name='inferencemodel',
            name='validation_error',
            field=models.TextField(blank=True),
        ),
    ]
