# Generated by Django 5.2.14 on 2026-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_inferencemodel_artifact_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencemodel',
            name='provider',
            field=models.CharField(choices=[('LOCAL', 'Upload local'), ('HUGGING_FACE', 'Hugging Face'), ('OLLAMA', 'Ollama')], default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='inferencemodel',
            name='source',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='inferencemodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PENDING', max_length=16),
        ),
    ]
