# Generated by Django 5.2.14 on 2026-08-14 02:07

import django.db.models.deletion
import quality.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_inferencemodel_provider_inferencemodel_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('task', models.CharField(blank=True, choices=[('DETECTION', 'Detection'), ('CLASSIFICATION', 'Classification'), ('POSE', 'Pose'), ('SEGMENTATION', 'Segmentation')], max_length=24)),
                ('format', models.CharField(choices=[('YOLO', 'YOLO'), ('COCO', 'COCO JSON'), ('CLASS_FOLDERS', 'Classification folders'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=24)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], db_index=True, default='PROCESSING', max_length=16)),
                ('source_path', models.CharField(max_length=500)),
                ('source_kind', models.CharField(choices=[('ZIP', 'ZIP'), ('FOLDER', 'Folder')], max_length=16)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('annotation_count', models.PositiveIntegerField(default=0)),
                ('missing_label_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('model_file', models.FileField(storage=quality.models.ModelStorage(), upload_to='evaluation/')),
                ('model_classes', models.JSONField(default=list)),
                ('class_mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_models', to='quality.evaluationdataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=16)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('per_class_metrics', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to='quality.evaluationdataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='quality.evaluationmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_evaluation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationDatasetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('annotation_count', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='quality.evaluationdataset')),
            ],
            options={
                'ordering': ['external_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'external_id'), name='unique_evaluation_dataset_class')],
            },
        ),
    ]
