# Generated by Django 5.1.7 on 2026-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_evaluationdataset_evaluationmodel_modelevaluationrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationmodel',
            name='detected_task',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='evaluationmodel',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationmodel',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='evaluationmodel',
            name='status',
            field=models.CharField(choices=[('ANALYZING', 'Analyzing'), ('READY', 'Ready'), ('ERROR', 'Error')], db_index=True, default='ANALYZING', max_length=16),
        ),
    ]
