# Generated by Django 5.1.7 on 2026-08-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_evaluationmodel_detected_task_evaluationmodel_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevaluationrun',
            name='preview',
            field=models.JSONField(default=dict),
        ),
    ]
