# Generated by Django 5.1.7 on 2026-08-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_client_project_rules'),
        ('quality', '0011_modelevaluationrun_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationdataset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_datasets', to='annotations.project'),
        ),
    ]
