# Generated by Django 5.1.7 on 2026-08-14 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_client_project_rules'),
        ('quality', '0012_evaluationdataset_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationdataset',
            name='project',
        ),
        migrations.AddField(
            model_name='evaluationdataset',
            name='client_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_datasets', to='annotations.clientproject'),
        ),
        migrations.AddField(
            model_name='evaluationdataset',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_datasets', to='annotations.rule'),
        ),
    ]
