# Generated by Django 5.1.7 on 2026-08-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_remove_evaluationdataset_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationdataset',
            name='rule',
        ),
    ]
