# Generated by Django 5.1.7 on 2026-08-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_remove_evaluationdataset_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluationFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=500)),
                ('output', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='quality.modelevaluationrun')),
            ],
            options={
                'ordering': ['frame_index'],
                'constraints': [models.UniqueConstraint(fields=('run', 'frame_index'), name='unique_model_evaluation_frame')],
            },
        ),
    ]
