from django.urls import path
from . import views

urlpatterns = [
    path("model-quality/", views.model_quality_workspace, name="model-quality-workspace"),
    path("model-quality/new/", views.create_model_quality_workspace, name="model-quality-create"),
    path("model-quality/tasks/<int:dataset_pk>/edit/", views.edit_model_quality_task, name="model-quality-task-edit"),
    path("model-quality/tasks/<int:dataset_pk>/delete/", views.delete_model_quality_task, name="model-quality-task-delete"),
    path("api/model-quality/datasets/", views.upload_evaluation_dataset, name="model-quality-dataset-upload"),
    path("api/model-quality/dataset-uploads/", views.initialize_evaluation_dataset_upload, name="model-quality-upload-init"),
    path("api/model-quality/dataset-uploads/<int:dataset_pk>/chunks/", views.upload_evaluation_dataset_chunk, name="model-quality-upload-chunk"),
    path("api/model-quality/dataset-uploads/<int:dataset_pk>/finalize/", views.finalize_evaluation_dataset_upload, name="model-quality-upload-finalize"),
    path("api/model-quality/dataset-uploads/<int:dataset_pk>/", views.evaluation_dataset_upload_status, name="model-quality-upload-status"),
    path("api/model-quality/datasets/<int:dataset_pk>/models/", views.upload_evaluation_model, name="model-quality-model-upload"),
    path("api/model-quality/models/<int:model_pk>/", views.evaluation_model_status, name="model-quality-model-status"),
    path("api/model-quality/models/<int:model_pk>/delete/", views.delete_evaluation_model, name="model-quality-model-delete"),
    path("api/model-quality/models/<int:model_pk>/mapping/", views.confirm_evaluation_model_mapping, name="model-quality-model-mapping"),
    path("api/model-quality/datasets/<int:dataset_pk>/runs/", views.create_model_evaluation_run, name="model-quality-run-create"),
    path("api/model-quality/runs/<int:run_pk>/", views.model_evaluation_run_status, name="model-quality-run-status"),
    path("model-quality/runs/<int:run_pk>/", views.model_evaluation_run_viewer, name="model-quality-run-viewer"),
    path("api/model-quality/runs/<int:run_pk>/frames/<int:frame_index>/", views.model_evaluation_frame_data, name="model-quality-run-frame-data"),
    path("api/model-quality/runs/<int:run_pk>/frames/<int:frame_index>/image/", views.model_evaluation_frame_image, name="model-quality-run-frame-image"),
    path("model-quality/runs/<int:run_pk>/export/", views.export_model_evaluation_run, name="model-quality-run-export"),
    path("model-quality/runs/<int:run_pk>/frames/<int:frame_index>/export/", views.export_model_evaluation_frame, name="model-quality-run-frame-export"),
    path("api/model-quality/runs/<int:run_pk>/preview-image/", views.model_evaluation_preview_image, name="model-quality-run-preview-image"),
    path("system/", views.system_dashboard, name="quality-system-dashboard"),
    path("system/models/", views.system_models, name="quality-system-models"),
    path("system/models/<int:model_pk>/edit/", views.edit_system_model, name="quality-system-model-edit"),
    path("system/models/<int:model_pk>/retry/", views.retry_system_model, name="quality-system-model-retry"),
    path("system/models/<int:model_pk>/delete/", views.delete_system_model, name="quality-system-model-delete"),
    path("projects/<int:project_pk>/quality/", views.dashboard, name="quality-dashboard"),
    path("projects/<int:project_pk>/quality/freeze-gt/", views.freeze_gt, name="quality-freeze-gt"),
    path("projects/<int:project_pk>/quality/test-cases/", views.create_test_case, name="quality-create-case"),
    path("projects/<int:project_pk>/quality/test-cases/<int:case_pk>/run/", views.run_test_case, name="quality-run-case"),
    path("projects/<int:project_pk>/quality/runs/<int:run_pk>/", views.run_detail, name="quality-run-detail"),
]
