# Generated by Django 5.1.7 on 2026-08-18 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_project_schema_jobs_shapes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAnnotationFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('kind', models.CharField(choices=[('detector', 'Detection'), ('pose', 'Pose / Skeleton')], max_length=16)),
                ('spec', models.JSONField(default=list, help_text='CVAT-compatible model label specification')),
                ('enabled', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutoAnnotationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('threshold', models.FloatField(default=0.25)),
                ('cleanup', models.BooleanField(default=False)),
                ('mapping', models.JSONField(default=dict)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('shapes_created', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='annotations.autoannotationfunction')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_annotation_runs', to='annotations.annotationtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
