# Generated by Django 5.1.7 on 2026-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_autoannotationfunction_autoannotationrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxannotation',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='labelclass',
            name='prompt',
        ),
    ]
